### ISSUE TITLE
Mudar Inputs de Periodo para o tipo "Date"

### ISSUE THREAD

**Issue by juanozorio** [arijunior2020/gerador-curriculo#4]
Quando o usuário cadastrar as datas, seria interessante ter o input do tipo "date", com o mês o ano.

`<input id="date" type="date" />`

Ficaria mais fácil para o usuário preencher, e além disso, ficaria padronizado no PDF

![image](https://github.com/arijunior2020/gerador-curriculo/assets/58236892/9bab5ef8-db42-4b3c-ab30-e67edc3949e6)

**Comment by arijunior2020** [comment]
> Quando o usuário cadastrar as datas, seria interessante ter o input do tipo "date", com o mês o ano.
> 
> `<input id="date" type="date" />`
> 
> Ficaria mais fácil para o usuário preencher, e além disso, ficaria padronizado no PDF
> 
> ![image](https://private-user-images.githubusercontent.com/58236892/333847947-9bab5ef8-db42-4b3c-ab30-e67edc3949e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTY1NTUsIm5iZiI6MTcyMzY1NjI1NSwicGF0aCI6Ii81ODIzNjg5Mi8zMzM4NDc5NDctOWJhYjVlZjgtZGI0Mi00YjNjLWFiMzAtZTY3ZWRjMzk0OWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE3MjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOWI4MmI0NTc5ZWUwM2IzYjYwZGMwNzI3MDE2NTVkNjk4NjMxODBmMTg3NzcxMmQ0NDBkMWRlZTMxNzM4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afiLkkSrwe6JwlciO69B9GXrmRpvuY7MtdLo8vWj5_U)

Boa, irei realizar o ajuste, valeu pela contribuição.

**Comment by arijunior2020** [comment]
Alteração realizada. Obrigado!

**Comment by arijunior2020** [comment]
Alteração realizada. Obrigado!
